# Generated by Django 6.0 on 2026-01-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_buyingrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyingrequest',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='buyingrequest',
            old_name='phone',
            new_name='customer_phone',
        ),
    ]
