# Generated by Django 6.0 on 2026-01-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_name_buyingrequest_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyingrequest',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='buyingrequest',
            name='message',
        ),
    ]
